### ISSUE TITLE
How to run augmentation policy search on new dataset?

### ISSUE THREAD

**Issue by HanielF** [MSU-MLSys-Lab/DeepAA#1]
Only CIFAR-10/100 and ImageNet are included in README on how to run augmentation policy search on them. 

Now i want to use a new dataset, and different from ImageNet, the new dataset doesnot contain image classes label.

**Comment by zhengyu998** [comment]
Hi @HanielF, you will mainly need to modify functions `get_dataset()` and `get_augmentation()` in DeepAA_utils.py. You will also need to modify the `DataAugmentation` class in data_generator.py in order to let it accept and preprocess the custom data you supply.

**Comment by HanielF** [comment]
@zhengyu998 Thanks for your help! I will have a try later.
