### ISSUE TITLE
What's the use of function "step2_cal_JVP_jvpStep" in DeepAA_search.py?

### ISSUE THREAD

**Issue by myuansun** [MSU-MLSys-Lab/DeepAA#2]
As far as I know, it uses `tf.autodiff.ForwardAccumulator` to calculate the gradient importance of certain augmentation policy, but how is this process realized through `tf.autodiff.ForwardAccumulator`? I've checked the introduction of `tf.autodiff.ForwardAccumulator` on this [website](https://tensorflow.google.cn/versions/r2.1/api_docs/python/tf/autodiff/ForwardAccumulator) but still very puzzled about how gradient importance(a scalar) is calculated taking gradients(several vectors) and tangents(several vectors) with same shape as input. Could you please provide more explanations about this process or some other resources related to JVP for me to better understand it?Thanks!

**Comment by zhengyu998** [comment]
The `ForwardAccumulator` is an efficient way to compute the Jacobian-vector product. Inside the function `step2_cal_JVP_jvpStep`, we use `ForwardAccumulator` to compute Eqn. (9) in our paper, where  $G(x)^T$ is the **jacobian** and the term in the second parentheses is the **tangent** (vector). The **jacobian** is just a tack of per-example gradients. For example, for a network with M parameters and N input examples, the **jacobian** is an NxM matrix, the **tangent** is an M-dimensional vector, and the resulting jacobian-vector product is an N dimension vector.

**Comment by myuansun** [comment]
> The `ForwardAccumulator` is an efficient way to compute the Jacobian-vector product. Inside the function `step2_cal_JVP_jvpStep`, we use `ForwardAccumulator` to compute Eqn. (9) in our paper, where $G(x)^T$ is the **jacobian** and the term in the second parentheses is the **tangent** (vector). The **jacobian** is just a tack of per-example gradients. For example, for a network with M parameters and N input examples, the **jacobian** is an NxM matrix, the **tangent** is an M-dimensional vector, and the resulting jacobian-vector product is an N dimension vector.

I see. Thanks for your reply!
