### ISSUE TITLE
ImportError: cannot import name 'adjust_learning_rate_resnet' from 'DeepAA_evaluate.lr_scheduler'

### ISSUE THREAD

**Issue by rain152** [MSU-MLSys-Lab/DeepAA#3]
The file DeepAA_evaluate/lr_sheduler seems to be missed...

**Comment by zhengyu998** [comment]
@rain152 Thank you for pointing this out! I have uploaded the file `DeepAA_evaluate/lr_scheduler.py`. It should be fixed now.
