### ISSUE TITLE
FileNotFoundError: 

### ISSUE THREAD

**Issue by ghost** [MSU-MLSys-Lab/DeepAA#4]
First, I created the conda environment and I ran the first command with DeepAA_search.py on cifar10. I didn’t have any problem except some library conflicts . I searched a compatible version of TensorFlow-probability with the environment to solve this.  To clarify, I’m working on AWS EC2.

When I run the second command: train.py for the dataset cifar10, I get an error: FileNotFoundError: [Errno 2] No such file or directory: 'ckpt/DeepAA_cifar10.

In the repository DeepAA_evaluate, there is no ckpt repository. Should I make it myself? what should the file DeepAA_cifar10.pth contain?

**Comment by zhengyu998** [comment]
Hi @CapGStudent , you just need to run `mkdir ckpt` before running `python -m DeepAA_evaluate.train ...` I have updated README accordingly.

**Comment by zhengyu998** [comment]
You may just leave `./ckpt` folder blank, and the checkpoint `DeepAA_cifar10.pth` will be automatically saved to the folder every 20 epochs.
