### ISSUE TITLE
Can't run DeepAA_evaluate.train

### ISSUE THREAD

**Issue by leodmel** [MSU-MLSys-Lab/DeepAA#5]
1. Tried to run `DeepAA_search` on Cifar100 with command `python3 DeepAA_search.py --dataset cifar100 --n_classes 100 --use_model WRN_40_2 --n_policies 6 --search_bno 1024 --pretrain_lr 0.1 --seed 1 --batch_size 128 --test_batch_size 512 --policy_lr 0.025 --l_mags 13 --use_pool --pretrain_size 5000 --nb_epochs 45 --EXP_G 16 --EXP_gT_factor=4 --train_same_labels 16 2>&1 | tee SomeFile.txt`, it cause an assertion failure 
```
Traceback (most recent call last):
  File "DeepAA_search.py", line 170, in <module>
    pretrain()
  File "DeepAA_search.py", line 144, in pretrain
    images, labels = get_pretrain_data()
  File "DeepAA_search.py", line 115, in get_pretrain_data
    use_post_aug=True, pool=pool)
  File "/opt/tiger/app/DeepAA/data_generator.py", line 184, in __call__
    self.check_data_type(images, labels)
  File "/opt/tiger/app/DeepAA/data_generator.py", line 179, in check_data_type
    assert type(labels[0]) == np.uint8
AssertionError
```
2. Ran `DeepAA_evaluate` on Cifar10 `python3 -m DeepAA_evaluate.train -c confs/wresnet28x10_cifar10_DeepAA_1.yaml --dataroot ./data --save ckpt/DeepAA_cifar10.pth --tag Exp_DeepAA_cifar10` incurred
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/tiger/app/DeepAA/DeepAA_evaluate/train.py", line 482, in <module>
    assert world_size == C.get()['gpus'], f"Did not specify the number of GPUs in Config with which it was started: {world_size} vs {C.get()['gpus']}"
AssertionError: Did not specify the number of GPUs in Config with which it was started: 8 vs 1
```

**Comment by zhengyu998** [comment]
1. Regarding your first question, you can just comment out the "assert" line, since the label of cifar100 is np.int64 instead of np.unit8. In our paper, we only search data augmentation policy on CIFAR10 and apply the obtained augmentation on both CIFAR10/100, so if you want to search on CIFAR100, the optimal hyper-parameters might be different.

2. Regarding your second question, you need to specify the GPUs by running:
```bash
export CUDA_VISIBLE_DEVICES=0
```
