### ISSUE TITLE
Computation time

### ISSUE THREAD

**Issue by JulietteMarrie** [MSU-MLSys-Lab/DeepAA#6]
Hi,
In your paper, you indicate that search on CIFAR10/100 takes 9 GPU hours. In my case, it takes almost 9 hours in total using 8 GPus V100, meaning around 70 GPU hours. Is it normal or do I do something wrong? 
Thanks!
Juliette

**Comment by zhengyu998** [comment]
Hi Juliette,

The running time depends on the parameters used for training, we deliberately set larger training parameters (and training budget) in the open-sourced version as it could be safer and more stable for users to try on other datasets. You may half the following parameters to finish running in almost 1 hour on an 8-GPU machine.

```bash
--search_bno 1024 --test_batch_size 512 --EXP_G 16 --EXP_gT_factor 4  --train_same_labels 16
```
