### ISSUE TITLE
What is the result?

### ISSUE THREAD

**Issue by jsjs0827** [MSU-MLSys-Lab/DeepAA#8]
After training, is there a specific policy for the dataset?Where is the result?

**Comment by zhengyu998** [comment]
Hi,

You can find the results in our paper https://arxiv.org/abs/2203.06172.

The augmentation policies for CIFAR and ImageNet are saved [here](https://github.com/MSU-MLSys-Lab/DeepAA/blob/master/policy_port).

Please refer to [README](https://github.com/MSU-MLSys-Lab/DeepAA/blob/master/README.md) on how to search and evaluate the augmentation policy.

**Comment by xhlho** [comment]
请问经过训练可以得到数据增强后的图像吗？还是只有概念结果

**Comment by zhengyu998** [comment]
@xhlho 
> 请问经过训练可以得到数据增强后的图像吗？还是只有概念结果

训练结果是 augmentation policy，例如rotate多少度。可以用得到的 augmentation policy 来增强数据。
